openapi: 3.1.0

info:
  title: Prompt Builder API
  version: 1.0.0

paths:
  /users:
    get:
      summary: List all users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /templates:
    get:
      summary: List all prompt templates
      responses:
        "200":
          description: A list of prompt templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PromptTemplate"

components:
  schemas:
    PromptVariable:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        description:
          type: string

    PromptTemplate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        template:
          type: string
        variables:
          type: array
          items:
            $ref: "#/components/schemas/PromptVariable"

    PromptTemplateInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        template:
          type: string
        variables:
          type: array
          items:
            $ref: "#/components/schemas/PromptVariable"

    PromptInput:
      type: object
      properties:
        templateId:
          type: string
        values:
          type: object
          additionalProperties: true

    PromptResult:
      type: object
      properties:
        id:
          type: string
        input:
          type: object
          additionalProperties: true
        output:
          type: string
        createdAt:
          type: string
          format: date-time

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
