injectWorkspacePackages: true
sharedWorkspaceLockfile: true
includeWorkspaceRoot: true
packages:
  - "./**/*"
catalog:
  "@dotenvx/dotenvx": ^1.44.1
  "chalk": ^5.4.1
  "husky": ^9.1.7
  "prisma": ^6.8.2
  "prisma-dbml-generator": ^0.12.0
  "semver": ^7.7.2
  "typescript": "~5.6.3"
