// DO NOT EDIT. This file is automatically generated.

declare type User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

declare type UserInput = {
  name: string;
  email: string;
  userId: string;
};

declare type Template = {
  id: string;
  name: string;
  description: string;
  template: string;
  createdAt: string;
  updatedAt: string;
};

declare type TemplateInput = {
  id: string;
  user: string;
  name: string;
  description: string;
  template: string;
};

declare type Service = {
  id: string;
  name: string;
  description: string;
  private: boolean;
  templates: Template[] | null;
  users: User[] | null;
  createdAt: string;
  updatedAt: string;
};

declare type ServiceInput = {
  name: string;
  private: boolean;
  description: string;
  userId: string;
};
