// DO NOT EDIT. This file is automatically generated.

declare type ServicesOnUsers = {
	serviceId: string;
	userId: string;
}

declare type User = {
	updatedAt: string;
	createdAt: string;
	services: ServicesOnUsers;
	password: string;
	email: string;
	name: string;
	id: string;
}

declare type PostUserInput = {
	name: string;
	email: string;
	userId: string;
}

declare type TemplateInput = {
	updatedAt: string;
	createdAt: string;
	templateId: string;
	input: string;
	id: string;
}

declare type TemplatesOnServices = {
	serviceId: string;
	templateId: string;
}

declare type Template = {
	updatedAt: string;
	createdAt: string;
	input: TemplateInput;
	services: TemplatesOnServices;
	template: string;
	description: string;
	name: string;
	id: string;
}

declare type PostTemplateInput = {
	name: string;
	description: string;
	template: string;
	userId: string;
}

declare type PostTemplateInputInput = {
	name: string;
	template: string;
	userId: string;
}

declare type Service = {
	updatedAt: string;
	createdAt: string;
	templates: TemplatesOnServices;
	users: ServicesOnUsers;
	description: string;
	private: boolean;
	name: string;
	id: string;
}

declare type PostServiceInput = {
	name: string;
	private: boolean;
	description: string;
	userId: string;
}
