// DO NOT EDIT. This file is automatically generated.

declare type User = {
	updatedAt: string;
	createdAt: string;
	password: string;
	email: string;
	name: string;
	id: string;
}

declare type PostUserInput = {
	name: string;
	email: string;
	userId: string;
}

declare type UserResponse = {
	user: User;
	token: string;
	error: error;
}

declare type TemplateInput = {
	updatedAt: string;
	createdAt: string;
	templateId: string;
	input: string;
	id: string;
}

declare type Template = {
	updatedAt: string;
	createdAt: string;
	input: TemplateInput;
	template: string;
	description: string;
	name: string;
	id: string;
}

declare type PostTemplateInput = {
	name: string;
	description: string;
	template: string;
	userId: string;
}

declare type PostTemplateInputInput = {
	name: string;
	template: string;
	userId: string;
}

declare type Service = {
	updatedAt: string;
	createdAt: string;
	description: string;
	private: boolean;
	name: string;
	id: string;
}

declare type PostServiceInput = {
	name: string;
	private: boolean;
	description: string;
	userId: string;
}

declare type ServiceResponse = {
	templates: Template[] | null;
	users: User[] | null;
	updatedAt: string;
	createdAt: string;
	description: string;
	private: boolean;
	name: string;
	id: string;
}

declare type error = unknown;
