dotenvx encrypt --env-file frontend/.env.test
dotenvx encrypt --env-file frontend/.env.local
dotenvx encrypt --env-file frontend/.env.development
dotenvx encrypt --env-file frontend/.env.staging
dotenvx encrypt --env-file frontend/.env.production
dotenvx encrypt --env-file http/.env.test
dotenvx encrypt --env-file http/.env.local
dotenvx encrypt --env-file http/.env.development
dotenvx encrypt --env-file http/.env.staging
dotenvx encrypt --env-file http/.env.production
