FROM golang:1.23 as builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest
RUN go install github.com/99designs/gqlgen@latest

RUN mv ./bin/air ./air

RUN chmod 755 ./air

EXPOSE 3333

CMD ["air","-c",".air.toml"]
