name: instructor-local-dev
version: "3.8"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend.dev
    volumes:
      - ../frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../http
      dockerfile: ../docker/Dockerfile.backend.dev
    volumes:
      - ../http:/usr/src/app
    ports:
      - "3333:3333"
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
