FROM node:22.12-alpine3.20 AS base

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./public/ ./public
COPY ./src/ ./src
COPY ./components.json ./components.json
COPY ./eslint.config.mjs ./eslint.config.mjs
COPY ./index.html ./index.html
COPY ./package.json ./package.json
COPY ./prettier.config.json ./prettier.config.json
COPY ./tailwind.config.ts ./tailwind.config.ts
COPY ./tsconfig.json ./tsconfig.json
COPY ./vite.config.ts ./vite.config.ts

RUN pnpm i

FROM node:22.12-alpine3.20 AS runner

RUN npm install -g pnpm

WORKDIR /usr/src/app

ENV FRONTEND_PORT=3001

COPY --from=base /usr/src/app/ ./

EXPOSE 3001

CMD ["pnpm", "dev"]
