FROM node:22.12-alpine3.20 AS base

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY . .

RUN pnpm install

FROM node:22.12-alpine3.20 AS runner

RUN npm install -g pnpm

WORKDIR /usr/src/app

ENV FRONTEND_PORT=3001

COPY --from=base /usr/src/app/ .

EXPOSE 3001

CMD ["pnpm", "dev"]
