// DO NOT EDIT. This file is automatically generated.

package model

type TemplatesOnServices struct {
	ServiceID  string
	TemplateID string
}

type ServicesOnUsers struct {
	ServiceID string
	UserID    string
}

type TemplateInput struct {
	UpdatedAt  string
	CreatedAt  string
	TemplateID string
	Input      string
	ID         string
}

type Template struct {
	UpdatedAt   string
	CreatedAt   string
	Input       TemplateInput
	Services    TemplatesOnServices
	Template    string
	Description string
	Name        string
	ID          string
}

type Service struct {
	UpdatedAt   string
	CreatedAt   string
	Templates   TemplatesOnServices
	Users       ServicesOnUsers
	Description string
	Private     bool
	Name        string
	ID          string
}

type User struct {
	UpdatedAt string
	CreatedAt string
	Services  ServicesOnUsers
	Password  string
	Email     string
	Name      string
	ID        string
}
