// DO NOT EDIT. This file is automatically generated.

package model

type InputsOnTemplates struct {
	InputID string
	TemplateID string
}

type TemplatesOnServices struct {
	ServiceID string
	TemplateID string
}

type ServicesOnUsers struct {
	ServiceID string
	UserID string
}

type Input struct {
	UpdatedAt string
	CreatedAt string
	TemplateID string
	Type string
	Description string
	Input string
	ID string
}

type Template struct {
	UpdatedAt string
	CreatedAt string
	Template string
	Description string
	Name string
	ID string
}

type Service struct {
	UpdatedAt string
	CreatedAt string
	Description string
	Private bool
	Name string
	ID string
}

type User struct {
	UpdatedAt string
	CreatedAt string
	Role string
	Password string
	Email string
	Name string
	ID string
}

