openapi: 3.1.3

info:
  title: Prompt Builder API
  version: 1.0.0

paths:
  /templates:
    get:
      summary: List all prompt templates
      responses:
        "200":
          description: A list of prompt templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PromptTemplate"
    post:
      summary: Create a new prompt template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptTemplateInput"
      responses:
        "201":
          description: Template created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplate"

  /templates/{id}:
    get:
      summary: Get a prompt template by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The requested template
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptTemplate"

  /prompt:
    post:
      summary: Submit values to a prompt template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptInput"
      responses:
        "200":
          description: LLM-generated result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromptResult"

components:
  schemas:
    PromptVariable:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        description:
          type: string

    PromptTemplate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        template:
          type: string
        variables:
          type: array
          items:
            $ref: "#/components/schemas/PromptVariable"

    PromptTemplateInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        template:
          type: string
        variables:
          type: array
          items:
            $ref: "#/components/schemas/PromptVariable"

    PromptInput:
      type: object
      properties:
        templateId:
          type: string
        values:
          type: object
          additionalProperties: true

    PromptResult:
      type: object
      properties:
        id:
          type: string
        input:
          type: object
          additionalProperties: true
        output:
          type: string
        createdAt:
          type: string
          format: date-time
