name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: TypeScript CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Package Manager
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: true
      - name: Run
        run: make test
